version: 2.1

jobs:
  build-and-test:
    docker:
      - image: moveworkforward/atlassian-sdk
    steps:
      - checkout
      - run:
          name: Run unit tests
          command: atlas-unit-test
  deploy-to-staging:    
    docker:
      - image: moveworkforward/atlassian-sdk
    steps:
      - run:
          name: Deploy to staging
          command: echo "Deploying artifact to staging environment"  
  deploy-to-production:    
    docker:
      - image: moveworkforward/atlassian-sdk
    steps:
      - run:
          name: Deploy to production
          command: echo "Deploying artifact to production environment"           
workflows:
  build-test-and-deploy:
    jobs:
      - build-and-test
      - deploy-to-staging:
          requires:
            - build-and-test
      - deploy-to-production:
          requires:
            - deploy-to-staging

