version: 2.1

jobs:
  build-and-test:
    docker:
      - image: moveworkforward/atlassian-sdk
    steps:
      - checkout
      - run:
          name: Run unit tests
          command: atlas-unit-test
workflows:
  run-unit-tests:
    jobs:
      - build-and-test

