version: 2.1

orbs:
  compass: atlassian-labs/compass@0.1.3
  jira: circleci/jira@2.1.0

jobs:
  build-and-test:
    docker:
      - image: moveworkforward/atlassian-sdk
    steps:
      - checkout
      - run:
          name: Run unit tests
          command: echo "Running unit tests"
  deploy-to-staging:    
    docker:
      - image: moveworkforward/atlassian-sdk
    steps:
      - run:
          name: Deploy to staging
          command: echo "Deploying artifact to staging environment"  
      - jira/notify: 
          environment: staging 
          environment_type: staging 
          pipeline_id: << pipeline.id >>
          pipeline_number: << pipeline.number >>
  deploy-to-production:    
    docker:
      - image: moveworkforward/atlassian-sdk
    steps:
      - run:
          name: Deploy to production
          command: echo "Deploying artifact to production environment"  
      - jira/notify: 
          environment: production 
          environment_type: production 
          pipeline_id: << pipeline.id >>
          pipeline_number: << pipeline.number >>         
      
workflows:
  build-test-and-deploy:
    jobs:
      - build-and-test
      - deploy-to-staging:
          context: JIRA_WEBHOOK_URL
          requires:
            - build-and-test                      
      - deploy-to-production:
          context: JIRA_WEBHOOK_URL
          filters:
            branches:
              only:
                - master
          requires:
            - deploy-to-staging        
          post-steps:
            - compass/notify_deployment:
                environment: production
                environment_type: production
            
      

