version: 2.1

jobs:
  build-and-test:
    docker:
      - image: moveworkforward/atlassian-sdk
    steps:
      - checkout
      - run:
          name: Run unit tests
          command: atlas-unit-test
  deploy:    
    steps:
      - run:
          name: Deploy to staging
          command: echo "Deploying artifact to staging environment"  
workflows:
  run-unit-tests:
    jobs:
      - build-and-test
  deploy-to-staging:
    jobs:
      - deploy

