version: 2.1

jobs:
  build-and-test:
    docker:
      - image: moveworkforward/atlassian-sdk
    steps:
      - checkout
      - run:
          name: Run unit tests
          command: atlas-unit-test
  deploy-staging:
    steps:
      - run:
          name: Deploy to staging
          command: echo "Deploying artifact to staging environment"
  deploy-production:
    steps:
      - run:
          name: Deploy to production
          command: echo "Deploying artifact to production environment"          
workflows:
  run-unit-tests:
    jobs:
      - build-and-test
  deploy-to-staging:
    jobs:
      - deploy-staging
  deploy-to-production:
    jobs:
      - deploy-production

