version: 2.1

orbs:
  compass: atlassian-labs/compass@0.1.3

jobs:
  build-and-test:
    docker:
      - image: moveworkforward/atlassian-sdk
    steps:
      - checkout
      - run:
          name: Run unit tests
          command: atlas-unit-test
  deploy-to-staging:    
    docker:
      - image: moveworkforward/atlassian-sdk
    steps:
      - run:
          name: Deploy to staging
          command: echo "Deploying artifact to staging environment"  
  deploy-to-production:    
    docker:
      - image: moveworkforward/atlassian-sdk
    steps:
      - run:
          name: Deploy to production
          command: echo "Deploying artifact to production environment"           
workflows:
  build-test-and-deploy:
    jobs:
      - build-and-test
      - deploy-to-staging:
          context:
            - compass-integration-crossprod.atlassian.net
          requires:
            - build-and-test
          post-steps:
            - compass/notify_deployment                       
      - deploy-to-production:
          context:
            - compass-integration-crossprod.atlassian.net      
          requires:
            - deploy-to-staging        
          post-steps:
            - compass/notify_deployment
      

